kind: pipeline
type: docker
name: test_drone

steps:
  - name: maven build
    image: maven:latest
    pull: if-not-exists
    volumes:
      - name: maven-build
        path: /root/testDrone
      - name: maven-cache
        path: /root/.m2
    commands:
      - mvn -v
      - mvn clean install -DskipTests=true
      - cp target/*.jar /root/testDrone
      - cp Dockerfile /root/testDrone
      - cp docker-compose.yaml /root/testDrone
      - echo "Maven build DONE."

  - name: deploy
    pull: if-not-exists
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: SSH_HOST
      port: 22
      username:
        from_secret: SSH_USER
      password:
        from_secret: SSH_PASSWORD
      script:
        - cd /root/testDrone
        - ls -a
        - docker build -t localhost:5000/drone-demo:latest .
        - docker compose -f docker-compose.yaml up -d
        - docker images --filter "dangling=true" -q | xargs -r docker rmi
        - echo "Deploy DONE."

volumes:
  - name: maven-build
    host:
      path: /root/testDrone
  - name: maven-cache
    host:
      path: /root/drone-cache