kind: pipeline
type: ssh
name: deploy
server:
  host:
    from_secret: SSH_HOST
  user:
    from_secret: SSH_USER
  password:
    from_secret: SSH_PASSWORD
steps:
  - name: maven build
    commands:
      - docker run --rm 
        -v /root/testDrone:/root/build 
        -v /root/drone-cache:/root/.m2 
        -v $(pwd):/workspace
        -w /workspace 
        maven:latest 
        bash -c "mvn -v 
        && mvn clean install -DskipTests=true 
        && cp target/*.jar /root/build 
        && cp Dockerfile /root/build 
        && cp docker-compose.yaml /root/build"
      - ls -la /root/testDrone
      - echo "Maven build DONE."
  - name: docker build
    commands:
      - cd /root/testDrone
      - ls -a
      - docker build -t my-drone-demo:latest .
  - name: docker up
    commands:
      - docker compose -f docker-compose.yaml up -d
  - name: remove dangling images
    commands:
      - docker images --filter "dangling=true" -q | xargs -r docker rmi
  - name: clean up tmp files
    commands:
      - rm -rf /root/testDrone
      - echo "Temporary files cleaned."
  - name: deploy done
    commands:
      - echo "Deploy DONE. "