version: '3'
services:
  drone-demo:
    image: my-drone-demo:latest
    #container_name: my-drone-demo #Docker requires each container to have a unique name. Remove the custom name to scale the service.
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
    environment:
      - SERVER_PORT:8083
    ports:
      - "8081-8082:8083"
