version: '3'

services:
  drone-server:
    image: drone/drone:2
    container_name: drone-server
    privileged: true
    ports:
      - "8000:80"
      - "50000:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/root/drone-volumn:/data"
    environment:
      - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
      - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_SERVER_UNTRUSTED=false
      - DRONE_USER_CREATE=username:KuPjnn,machine:false,admin:true,token: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
    restart: always
    depends_on:
      - drone-runner

  drone-runner:
    image: drone/drone-runner-ssh
    container_name: drone-runner-ssh
    privileged: true
    environment:
      - DRONE_RPC_PROTO=${DRONE_RPC_PROTO}
      - DRONE_RPC_HOST=${DRONE_RPC_HOST}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=drone-runner
    restart: always
